// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserApi.Data;

#nullable disable

namespace UserApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526094224_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            CreatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(6745),
                            Deleted = false,
                            Description = "Người dùng mẫu",
                            Email = "nguyenvana@example.com",
                            Name = "Nguyen Van A",
                            UpdatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(7081)
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            CreatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(7705),
                            Deleted = false,
                            Description = "Dữ liệu mẫu thứ hai",
                            Email = "tranthib@example.com",
                            Name = "Tran Thi B",
                            UpdatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(7705)
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            CreatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(7707),
                            Deleted = false,
                            Description = "Dữ liệu mẫu thứ ba",
                            Email = "levanc@example.com",
                            Name = "Le Van C",
                            UpdatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(7708)
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            CreatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(7709),
                            Deleted = false,
                            Description = "Dữ liệu mẫu thứ tư",
                            Email = "phamthid@example.com",
                            Name = "Pham Thi D",
                            UpdatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(7710)
                        },
                        new
                        {
                            Id = 5,
                            Age = 32,
                            CreatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(7712),
                            Deleted = false,
                            Description = "Dữ liệu mẫu thứ năm",
                            Email = "hoangvane@example.com",
                            Name = "Hoang Van E",
                            UpdatedAt = new DateTime(2026, 5, 26, 16, 42, 22, 525, DateTimeKind.Local).AddTicks(7712)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
